### PR TITLE
Nathan/bug squashing

### LINKED ISSUE #175: Delete assessment bug
image

Current: Both delete assessment button delete assessment 2.
Change: First delete button deletes assessment 1 and second delete button delete assessment 2

### PR DESCRIPTION
**Pull request by nathantew14**
fixes #175

### CODE REVIEW

File: components/records/ConsultationForm.js [hunk 1]
```diff
@@ -56,11 +56,13 @@ export function ConsultationForm({
           className={`border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 mt-4 ${
             diagnosis.category === 'Please select...' ? 'bg-red-100' : ''
           }`}
-          name="type"
+          name="category"
```
Comment (keithxun) [inline components/records/ConsultationForm.js:59]: Good catch

File: components/records/ConsultationForm.js [hunk 2]
```diff
@@ -47,7 +47,7 @@ export function ConsultationForm({
           name="details"
           label={`Diagnosis ${index + 1}`}
           type="text"
-          value={formDetails.details}
+          value={diagnosis.details}
```
Comment (keithxun) [inline components/records/ConsultationForm.js:50]: image
Category of diagnoses is not captured when form is submitted.

**Comment by keithxun** [comment]
lgtm
