### PR TITLE
73-consult-bug

### LINKED ISSUE #73: Create Consult Bug
**Describe the bug**
A clear and concise description of what the bug is. And which page is it on? 
On create consultation page, when Referred for is 'Not Referred', the Referral Notes should be hidden.
`http://localhost:3000/records/patient-consultation?id=7&visit=13`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Patient Records'
2. Click on 'Create' Consultation
3. Scroll down to 'Referred for'
4. See that Referral Notes is still present

**Expected behaviour**
When the value of referred for is 'Not Referred', it should hide the referral notes.

**Screenshots**
Image

**Additional context**
Which browser are you using? **Chrome**

Commit hash of backend:
44afef8e1dca75e96370ea4c3095d08ff87b318d

Commit hash of frontend:
a0bcbb59d25a9bb542148b8c12337d19f58d063c

### PR DESCRIPTION
**Pull request by derrikzzz**
Description:
This PR aims to hide the referral notes when the option selected in the dropdown for 'Referred for (optional)'  is 'Not referred', to prevent users from entering details in referral notes when there's no referral. The change lies in conditionally rendering RHFInputField for referral_notes only when referred_for value !== ''.

Issue ticket number and link:
#73

### CODE REVIEW

File: src/components/records/consultation/ConsultationForm.tsx [hunk 1]
```diff
@@ -217,17 +217,20 @@ export function ConsultationForm({
...
+                <RHFInputField
+                  name="referral_notes"
+                  label="Referral Notes"
+                  type="textarea"
+                  placeholder="Type your referral notes here..."
+                  isRequired={true}
+                />
+              )
+            );
+          })()}
```
Comment (pohanson) [inline src/components/records/consultation/ConsultationForm.tsx]: Let's avoid using lambda function to return tsx component if possible? The issue is that initially `referred_for` is `undefined` which is different from `""`. 

`""` is used for `Not Referred` so how can we check for the case of `undefined`?

**Review by pohanson — CHANGES_REQUESTED** [review]
It doesn't work. On the first loading of the page, I can see Referred For as `Not Referred`, but there's still the Referral Notes shown
